version: "3"

services:
  directus:
    image: directus/directus:10.6.3
    ports:
      - 8055:8055
    volumes:
      - ./directus/database:/directus/database
      - ./directus/extensions:/directus/extensions
      - ./directus/uploads:/directus/uploads
    links:
      - keycloak
    depends_on:
      - keycloak
      # condition: service_healthy
    environment:
      KEY: "0fda9121-269d-44bd-91f2-4ff05be14b4b"
      SECRET: "86cb4a76-a4c6-4ce7-8181-b0445d95675c"

      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"

      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
      EXTENSIONS_AUTO_RELOAD: "true"

      PUBLIC_URL: "http://localhost:8055"

      AUTH_PROVIDERS: "keycloak"
      AUTH_KEYCLOAK_DRIVER: "openid"
      AUTH_KEYCLOAK_CLIENT_ID: "directus"
      AUTH_KEYCLOAK_CLIENT_SECRET: "**********"
      AUTH_KEYCLOAK_ISSUER_URL: "http://keycloak:8080/realms/collectivo/.well-known/openid-configuration"
      AUTH_KEYCLOAK_IDENTIFIER_KEY: "email"
      AUTH_KEYCLOAK_ALLOW_PUBLIC_REGISTRATION: "true"

      # REFRESH_TOKEN_COOKIE_DOMAIN: "http://localhost:8055"
      REFRESH_TOKEN_COOKIE_SECURE: "false"
      REFRESH_TOKEN_COOKIE_SAME_SITE: "lax"

      LOG_LEVEL: "debug"

  keycloak-db:
    image: postgres:15.4-alpine
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_FRONTEND_URL: ${KEYCLOAK_URL}
      KEYCLOAK_IMPORT: /tmp/collectivo-realm.json
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: "keycloak"
      KC_DB_URL_HOST: "keycloak-db"
      KC_DB_URL_PORT: 5432
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import:ro
      - ./keycloak/export:/tmp/export
      - ./keycloak/healthcheck.sh:/healthcheck.sh
    command: start-dev --import-realm
    healthcheck:
      # TODO: Not working
      test: ["CMD", "curl", "--fail", "http://keycloak:8080/realms/master"]
      interval: 5s
      timeout: 2s
      retries: 15
    depends_on:
      - keycloak-db
    ports:
      - "8080:8080"

volumes:
  keycloak-db-data:
